co_exp/co_exp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('detail_show.urls')),
]

co_exp/detail_show/urls.py
from django.urls import path,re_path
from . import views
from django.views.decorators.csrf import csrf_exempt
from .split_views import coexp, network, gene, heatmap,boxplot, blastAnalyse

app_name = 'detail_show'
urlpatterns = [
    path('', views.index, name='index'),

    re_path(r'co-expression$', coexp.co_expression, name='co-expression'),
    path('co-search', views.co_search, name='co-search'),

    re_path(r'network$', network.network_json, name='network'),
    path('search', views.search, name='search'),

    re_path(r'gene$', gene.gene_detail, name='gene'),
    re_path(r'heatmap$', heatmap.heatmap_json, name='heatmap'),
    re_path(r'boxplot$', boxplot.boxplot_json, name='boxplot'),

    path('blast', views.blast, name='blast'),
    path('blastAnalyse', blastAnalyse.blast_analyse, name='blastAnalyse'),

    path('404_not_found', views.not_found, name='404_not_found')
]
# handler404 = views.not_found

co_exp/detail_show/models.py
from django.db import models

# Create your models here.
class genelist(models.Model):
    geneaccession = models.CharField(max_length=15)
    coexpress_gene = models.CharField(max_length=15)
    cor = models.CharField(max_length=100)
    p_value = models.CharField(max_length=100)

class ontology(models.Model):
    geneaccession = models.CharField(max_length=15)
    geneontology = models.CharField(max_length=200)

class kegg(models.Model):
    geneaccession = models.CharField(max_length=15)
    genekegg = models.CharField(max_length = 100)

class descs(models.Model):
    geneaccession = models.CharField(max_length=15)
    description = models.CharField(max_length=200)
    alias = models.CharField(max_length=20)
    location = models.CharField(max_length=100)

class heatmap(models.Model):
    geneaccession = models.CharField(max_length=15)
    runid = models.CharField(max_length=12)
    tpm = models.CharField(max_length=20)
    tissue = models.CharField(max_length=15)

co_exp/detail_show/views.py
from django.shortcuts import render, render_to_response

# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect

def index(request):
    return render(request,'detail_show/home.html')


def co_search(request):
    return render(request, 'detail_show/co-search.html')


def search(request):
    return render(request, 'detail_show/gene_search.html')

def blast(request):
    return render(request, 'detail_show/blast.html')

def not_found(request):
    return render(request, 'detail_show/404.html')
    # return render_to_response('404.html')

co_exp/detail_show/templates/detail_show/404_not_found.html
<!DOCTYPE html>
<!--[if IE 8 ]><html class="no-js oldie ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]><html class="no-js oldie ie9" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html class="no-js" lang="en"> <!--<![endif]-->

{% load static %}
<head>

   <!--- basic page needs
   ================================================== -->
   <meta charset="utf-8">
	<title>404_NOT_FOUND</title>
	<meta name="description" content="">  
	<meta name="author" content="">

   <!-- mobile specific metas
   ================================================== -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

 	<!-- CSS
   ================================================== -->
   <link rel="stylesheet" href="{% static '404/css/base.css' %}">  
   <link rel="stylesheet" href="{% static '404/css/main.css' %}">
   <link rel="stylesheet" href="{% static '404/css/vendor.css' %}">     

   <!-- script
   ================================================== -->
	<script src="{% static '404/js/modernizr.js' %}"></script>

   <!-- favicons
	================================================== -->
	<link rel="icon" type="image/png" href="{% static '404/favicon.png' %}">

</head>

<body>

	<!-- header 
   ================================================== -->
   <header class="main-header">
   	<div class="row">
   		<div class="logo">
	         <a href="index.html">Quatro</a>
	      </div>   		
   	</div>   

   	<a class="menu-toggle" href="#"><span>Menu</span></a>	
   </header> <!-- /header -->

   <!-- navigation 
   ================================================== -->
   <nav id="menu-nav-wrap">

   	<h5>Site Pages</h5>   	
		<ul class="nav-list">
			<li><a href="#" title="">Home</a></li>
			<li><a href="#" title="">About</a></li>
			<li><a href="#" title="">Portfolio</a></li>
			<li><a href="#" title="">Blog</a></li>
			<li><a href="#" title="">FAQ</a></li>					
			<li><a href="#" title="">Contact</a></li>					
		</ul>

		<h5>Some Text</h5>  
		<p>Lorem ipsum Non non Duis adipisicing pariatur eu enim Ut in aliqua dolor esse sed est in sit exercitation eiusmod aliquip consequat.</p>

	</nav>

	<!-- main content
   ================================================== -->
   <main id="main-404-content" class="main-content-static">

   	<div class="content-wrap">

		   <div class="shadow-overlay"></div>

		   <div class="main-content">
		   	<div class="row">
		   		<div class="col-twelve">
			  		
			  			<h1 class="kern-this">404 Error.</h1>
			  			<p>
						Oooooops! Looks like nothing was found at this location.
						Maybe try on of the links below, click on the top menu
						or try a search?
			  			</p>

			  			<div class="search">
				      	<form>
								<input type="text" id="s" name="s" class="search-field" placeholder="Type and hit enter …">
							</form>
				      </div>	   			

			   	</div> <!-- /twelve --> 		   			
		   	</div> <!-- /row -->    		 		
		   </div> <!-- /main-content --> 
           <div class="copyrights">Collect from <a href="http://www.cssmoban.com/" >企业网站模板</a></div>

		   <footer>
		   	<div class="row">

		   		<div class="col-seven tab-full social-links pull-right">
			   		<ul>
				   		<li><a href="#"><i class="fa fa-facebook"></i></a></li>
					      <li><a href="#"><i class="fa fa-behance"></i></a></li>
					      <li><a href="#"><i class="fa fa-twitter"></i></a></li>
					      <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
					      <li><a href="#"><i class="fa fa-instagram"></i></a></li>   			
				   	</ul>
			   	</div>
		   			
		  			<div class="col-five tab-full bottom-links">
			   		<ul class="links">
				   		<li><a href="#">Homepage</a></li>
				         <li><a href="#">About</a></li>
				         <li><a href="mailto:joe@quatro.com">Report Error</a></li>			                    
				   	</ul>

				   	<div class="credits">
				   		<p>More Templates <a href="http://www.cssmoban.com/" target="_blank" title="模板之家">模板之家</a> - Collect from <a href="http://www.cssmoban.com/" title="网页模板" target="_blank">网页模板</a></p>
				   	</div>
			   	</div>   		   		

		   	</div> <!-- /row -->    		  		
		   </footer>

		</div> <!-- /content-wrap -->
   
   </main> <!-- /main-404-content -->

   <div id="preloader"> 
    	<div id="loader"></div>
   </div> 

   <!-- Java Script
   ================================================== --> 
   <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
   <script src="{% static '404/js/plugins.js' %}"></script>
   <script src="{% static '404/js/main.js' %}"></script>

</body>

</html>

co_exp/detail_show/templates/detail_show/co-expression.html
<!DOCTYPE html>

{% load static %}
<html lang="en">


<head>
    <meta charset="UTF-8">
    <title>co-exp</title>
    <link href="{% static 'css/co-expression.css' %}" rel="stylesheet" type="text/css">

    <!-- vis -->
    <link href="{% static 'css/vis.min.css' %}" rel="stylesheet">
    <!-- dataTables -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/jquery.dataTables.min.css' %}">	
    <link rel="stylesheet" type="text/css" href="{% static 'css/buttons.dataTables.min.css' %}">	

    <!-- vis -->
    <script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/vis.min.js' %}"></script>
    <!-- dataTables -->
    <script type="text/javascript" src="{% static 'js/jquery.dataTables.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/dataTables.buttons.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/buttons.html5.min.js' %}"></script>
    


</head>



<body>

<div class="body">
    <div class="h">
        <h2>Co Expression</h2>
    </div>

    {% if not_found_accession %}
    <div class="no_id"><pre>Cannot find <i>{{ not_found_accession }}</i>, maybe you should lower the threshold of the correlation coefficient.</pre></div>
    {% endif %}

    <div id="network" class="co-network"></div>
    <script>
        $("#network").html("<img src='{% static 'images/loading.gif' %}'/>");
        var parameter = 'genes='+'{{ accession }}' + '&cor='+'{{ co_cor }}';
        var s_url = "{% url 'detail_show:network' %}";
        var url = s_url+'?'+parameter;
    
        $.ajax({
            url: url,
            type: "get",
            dataType: "json",
            success: function (data) {
                data = JSON.parse(data);
                var nodesDataset = new vis.DataSet(data.nodes);
                var edgesDataset = new vis.DataSet(data.edges);
    
                var container = document.getElementById('network');
                var options = {
                    autoResize: true,
                    nodes: {
                        shape: 'dot',
                        size:5,
                        borderWidth:0,
                        borderWidthSelected:0,
                        font: '12px arial #333'
                    },
                    groups: {
                        geneGroup: {color:{background:'red'}, borderWidth:0,size:10}
                    },
                    physics:false,
                    edges: {
                        width: 0.2,
                        color: '#999',
                        smooth: {
                            type: 'continuous'
                        }
                    },
                    interaction: {
                        hover: true,
                        hideEdgesOnDrag: true,
                        tooltipDelay: 50
                    }
                };
                var data1 = {nodes: nodesDataset, edges: edgesDataset};
    
    
                var network = new vis.Network(container, data1, options);
    
                //network.on("click",neighbourhoodHighlight);
            }
        });
    </script>
    <div class="total">
        <p>Total: {{ node_number }} nodes; {{ edge_number }} edges</p>
    </div>


    <div class="table">
        <table id="datatable" class="display">
            <thead>
                <tr>
                    <th>Gene One</th>
                    <th>Gene Two</th>
                    <th>Pearson's R</th>
                    <th>P-value</th>
                </tr>
            </thead>
            <tbody>
            {% for item in gene_list %}
                <tr>
                    <td><a href="{% url 'detail_show:gene' %}?gene={{ item.geneaccession }}" target="view_window">{{ item.geneaccession }}</a></td>
                    <td><a href="{% url 'detail_show:gene' %}?gene={{ item.coexpress_gene }}" target="view_window">{{ item.coexpress_gene }}</a></td>
                    <td>{{ item.cor }}</td>
                    <td>{{ item.p_value }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <script>
        $(document).ready( function () {
            $('#datatable').DataTable({
                // "dom": '<"top"flB>rt<"bottom"ip><"clear">',
                "dom": '<"top"fB>rt<"bottom"ip><"clear">',
                buttons: [                      //set buttons
                    'pageLength',               //a direct replacement to the DataTables default length list
                    {
                        extend: 'csvHtml5',     //export data to a csv file
                        text: 'Data export'
                    }
                ],
                language: {                     //change the display on the 'pageLength' buttons
                    buttons: {
                        pageLength: {
                            _: "Show %d entries",
                            '-1': "Show all entries"
                        }
                    }
                },
                "lengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]] //lengthMenu adjust
            });
        } );
    </script>
</div>

</body>
</html>

co_exp/detail_show/templates/detail_show/co-search.html
<!DOCTYPE html>

{% load static %}
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>co-search</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/co-search.css' %}"/>

    <script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>

    <script>
        $(document).ready(function(){
            $('#eg_co-gene').click(function(){
                var eg=$('#eg_co-gene').text();
                $('#co-gene').val(eg);
            });
        });
    </script>
</head>

<body>
    <div class="d1">
        <form action="{% url 'detail_show:co-expression' %}" method="POST">
            <div>
                <label>Gene ID:</label><br/>
                <textarea id='co-gene' rows="10" cols="50" name="co-gene_ids" required></textarea>  <!-- required 属性规定必需在提交之前填写输入字段。 -->
                <br/>
                <span>
                    e.g.,&nbsp;<a href="#"><em id="eg_co-gene">TEA000001.1,TEA000003.1</em></a>
                </span>
            </div>
            <br/>
            <div>
                <label>Pearson's r-value:</label><br/>
                <input type="text" value="0.9" id="co-cor" name="cor"/>
            </div>
            <br/>
            <div>
                {% csrf_token %}
                <input type="submit" value="search" name='submitBtn' id="sub"/>
            </div>
        </form>
    </div>
</body>
</html>

co_exp/detail_show/templates/detail_show/detail.html
<!DOCTYPE html>

{% load static %}
<html lang="en">


<head>
    <meta charset="UTF-8">
    <title>co-exp</title>
    <link href="{% static 'css/detail.css' %}" rel="stylesheet">
</head>



<body>

<h1>gene page</h1>

<div class="d1">
    <form action="{% url 'detail_show:search' %}" method="POST" name="search">
        {% csrf_token %}
        <input type="text" name="gene_ids"/>
        <p>eg:TEA000001.1</p>
        <input type="submit" value="search" name='submitBtn'/>
    </form>
</div>
<br/>

<table class="ta">
    <tbody>
    <tr class="ta1">
        <!-- <td>Gene Accession</td> -->
        <!-- <td>Description</td> -->
        <!-- <td>Alias</td> -->
        <!-- <td>Location</td> -->
        <!-- <td>Gene Ontology:</td> -->
        <!-- <td>KEGG:</td> -->
        <th>geneaccession</th>
        <th>coexpress_gene</th>
        <th>cor</th>
        <th>p-value</th>
    </tr>
{% for item in gene_list.all %}
    <tr>
        <td>{{ item.geneaccession }}</td>
        <td>{{ item.coexpress_gene }}</td>
        <td>{{ item.cor }}</td>
        <td>{{ item.p_value }}</td>
        <!-- <td>{{ descs.geneaccession }}</td>
        <td>{{ descs.description }}</td>
        <td>{{ descs.alias }}</td>
        <td>{{ descs.location }}</td> -->
    </tr>
{% endfor %}
</tbody>
</table>


</body>
</html>

co_exp/detail_show/templates/detail_show/gene_detail.html
<!DOCTYPE html>

{% load static %}
<html lang="en">


<head>
    <meta charset="UTF-8">
    <title>gene_detail</title>
    <link href="{% static 'css/gene.css' %}" rel="stylesheet" type="text/css">
    <!-- heatmap -->
    <script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/echarts.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/dataTool.min.js' %}"></script>
    <script>
        function click_a(divDisplay){
            if(document.getElementById(divDisplay).style.display != "block"){
                document.getElementById(divDisplay).style.display = "block";
                show.innerHTML = "Hide data";
            }
            else{
                document.getElementById(divDisplay).style.display = "none";
                show.innerHTML = "Show data";
            }
        }
        function click_b(divDisplay){
            if(document.getElementById(divDisplay).style.display != "block"){
                document.getElementById(divDisplay).style.display = "block";
            }
            else{
                document.getElementById(divDisplay).style.display = "none";
            }
        }
    </script>

    <!-- <script>
        $(document).ready(function () {
            $("#btn").click(function () {
                var b = $(this);
                var a = $("#data");
                if (a.hasClass("collapse in")) {
                    b.text('Show data');
                } else {
                    b.text('Hidden data');
                }
            })
        })
    </script> -->
</head>



<body>

<div class="body">
    <div class="h">
        <h2>gene_detail</h2>
    </div>

    {% if not_found_accession %}
    <div class="no_id"><pre>Cannot find <i>{{ not_found_accession }}</i> in database</pre></div>
    {% endif %}

    <div onclick="return click_a('data')" class="show" id="show"><a>Show data</a></div>
    <!-- <div class="show"><a data-toggle="collapse" href="#showtable" aria-expanded="false" id="btn">Show data</a></div> -->
    <div class="data" id="data">
        {% for item in details %}
        <div onclick="return click_b('{{ item.accession }}')" class="click"><a>{{ item.accession }}</a></div>
        <div class="table" id="{{ item.accession }}">
            <p>Gene Accession: {{ item.accession }}</p>
                <p>Description: {{ item.desc.description }}</p>
                <p>Alias：{{ item.desc.alias }}</p>
                <p>Location：{{ item.desc.location }}</p>
            <p>Gene Ontology:</p>
            {% for i in item.go_number %}
                <p>&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://amigo.geneontology.org/amigo/term/{{ i }}" target="view_window">{{ i }}</a></p>
            {% endfor %}
            <p>KEGG:</p>
            {% for i in item.ko_number %}
                <p>&nbsp;&nbsp;&nbsp;&nbsp;<a href="https://www.kegg.jp/dbget-bin/www_bget?ko:{{ i }}" target="view_window">{{ i }}</a></p>
            {% endfor %}
            <div id="boxplot_{{  item.accession  }}" class="boxplot"></div>
            <script type="text/javascript">
                $("#boxplot_{{  item.accession  }}").html("<img src='{% static 'images/loading.gif' %}'/>");
                var parameter = 'gene='+'{{ item.accession }}';
                var s_url = "{% url 'detail_show:boxplot' %}";
                var url = s_url+'?'+parameter;
            
                $.ajax({
                    url: url,
                    type: "get",
                    dataType: "json",
                    success: function (data) {
                        data = JSON.parse(data);
                        var myChart = echarts.init(document.getElementById('boxplot_{{  item.accession  }}'));
                        
                        // use dataTool.min.js echarts.dataTool.prepareBoxplotData
                        var box_data = echarts.dataTool.prepareBoxplotData(data[0].values);
                        var x_data = data[0].tissues;
            
                        option = {
                            title: [
                                {
                                    text: '{{  item.accession  }}',
                                    left: 'center',
                                },
                                {
                                    text: 'upper: Q3 + 1.5 * IQR \nlower: Q1 - 1.5 * IQR',
                                    borderColor: '#999',
                                    borderWidth: 1,
                                    textStyle: {
                                        fontSize: 10
                                    },
                                    // left: '80%',
                                    // top: '90%'
                                    right: 0,
                                    bottom: 0
                                }
                            ],
                            toolbox: {
                                show: true,
                                feature: {
                                    dataZoom: {
                                        yAxisIndex: 'none'
                                    },
                                    restore: {},
                                    saveAsImage: {}
                                }
                            },
                            tooltip: {
                                trigger: 'item',
                                axisPointer: {
                                    type: 'shadow'
                                }
                            },
                            grid: {
                                left: '10%',
                                right: '10%',
                                bottom: '15%'
                            },
                            xAxis: {
                                type: 'category',
                                data: x_data,
                                // boundaryGap: true,
                                // nameGap: 30,
                                splitArea: {
                                    show: false
                                },
                                axisLabel: {
                                    rotate: 60
                                },
                                splitLine: {
                                    show: false
                                }
                            },
                            yAxis: {
                                type: 'value',
                                name: 'Expression level(TPM)',
                                splitArea: {
                                    show: true
                                }
                            },
                            series: [
                                {
                                    name: 'boxplot',
                                    type: 'boxplot',
                                    data: box_data.boxData,
                                    tooltip: {
                                        formatter: function (param) {
                                            return [
                                                'Tissue ' + param.name + ': ',
                                                'upper: ' + param.data[5],
                                                'Q3: ' + param.data[4],
                                                'median: ' + param.data[3],
                                                'Q1: ' + param.data[2],
                                                'lower: ' + param.data[1]
                                            ].join('<br/>');
                                        }
                                    }
                                },
                                {
                                    name: 'outlier',
                                    type: 'scatter',
                                    data: box_data.outliers
                                }
                            ]
                        };
            
                        myChart.setOption(option);
                    }
                });
            </script>
        </div>
        {% endfor %}
    </div>
</div>


<div id="heatmap" class="heatmap"></div>
<script type="text/javascript">
    $("#heatmap").html("<img src='{% static 'images/loading.gif' %}'/>");
    var parameter = 'genes='+'{{ accession }}';
    var s_url = "{% url 'detail_show:heatmap' %}";
    var url = s_url+'?'+parameter;

    $.ajax({
        url: url,
        type: "get",
        dataType: "json",
        success: function (data) {
            data = JSON.parse(data);
            var myChart = echarts.init(document.getElementById('heatmap'));
            var genes = data[0].genes;
            var runs = data[0].ssrs;
            var exps = data[0].expression;
            var tissues = data[0].tissues;
            var ranges = data[0].ranges;

            // exp = exp.map(function (item) {
            //     return [item[1], item[0], item[2] || '-'];
            // });

            option = {
                // tooltip: {
                //     position: 'top'
                // },
                title: {
                    text:'Heat Map'
                },
                toolbox: {
                    show: true,
                    feature: {
                        dataZoom: {
                            yAxisIndex: 'none'
                        },
                        // dataView: {readOnly: false},
                        // magicType: {type: ['line', 'bar']},
                        restore: {},
                        saveAsImage: {}
                    }
                },
                tooltip: {
                    position: 'top',
                    formatter: function (params) {
                        return  'Gene：'+genes[params.value[1]]+'<br/>'+ 'Run：'+runs[params.value[0]]+'<br/>'+'TPM(log10)： '+params.value[2]+'<br/>'+'Tissue: '+tissues[params.value[0]];
                    }
                },
                animation: false,
                grid: {
                    height: '60%',
                    y: '10%',
                },
                xAxis: {
                    type: 'category',
                    data: runs,
                    splitArea: {
                        show: true
                    },
                    axisLabel: {
                        rotate: 60
                    },
                    splitLine: {
                        show: true
                    }
                },
                yAxis: {
                    type: 'category',
                    data: genes,
                    splitArea: {
                        show: true
                    }
                },
                dataZoom: [
                    {
                        type: 'slider',
                        show: true,
                        xAxisIndex: [0],
                        start: 0,
                        end: 100
                    },
                    {
                        type: 'slider',
                        show: true,
                        yAxisIndex: [0],
                        left: '94%',
                        start: 0,
                        end: 100
                    },
                    {
                        type: 'inside',
                        xAxisIndex: [0],
                        start: 0,
                        end: 100
                    },
                    {
                        type: 'inside',
                        yAxisIndex: [0],
                        start: 0,
                        end: 100
                    }
                ],
                visualMap: {
                    min: ranges[0],
                    max: ranges[1],
                    // min: -2,
                    // max: 6,
                    calculable: true,
                    inRange: {
                        // color: ['lightskyblue', '#78b8ed', 'red'],
                        color: ['lightskyblue', '#fffbbc', '#c4463a','red']
                        // color: ['white', 'blue']
                        // symbolSize: [30, 100]
                    },
                    realtime: true,
                    precision: 2,
                    align: 'left',
                    orient: 'horizontal',
                    left: 'center',
                    bottom: '10%',
                    itemHeight: 250,
                },
                series: [{
                    name: 'Punch Card',
                    type: 'heatmap',
                    data: exps,
                    // label: {
                    //     normal: {
                    //         color: '#0F0F0F',
                    //         show: true
                    //     }
                    // },
                    itemStyle: {
                        emphasis: {
                            shadowBlur: 10,
                            shadowColor: 'rgba(0, 0, 0, 0.5)'
                        }
                    }
                }]
            };
            myChart.setOption(option);
        }
    });
</script>

<div class="total">
    <a>Gene numbers: {{ heatmap_total.gene_num }}</a><br/>
    <a>Run number: {{ heatmap_total.run_num }}</a><br/>
    <a>Tissue number: {{ heatmap_total.tissue_num }}</a>
    <div class="tissue">
        {% for item in heatmap_total.tissues %}
        <a>{{ item }}</a>&nbsp;&nbsp;
        {% endfor %}
    </div>
</div>
</body>
</html>

co_exp/detail_show/templates/detail_show/gene_search.html
<!DOCTYPE html>

{% load static %}
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>search</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/co-search.css' %}"/>

    <script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>

    <script>
        $(document).ready(function(){
            $('#eg_gene').click(function(){
                var eg=$('#eg_gene').text();
                $('#gene').val(eg);
            });
        });
    </script>
</head>

<body>
    <div class="d1">
        <form action="{% url 'detail_show:gene' %}" method="POST">
            <div>
                <label>Gene ID:</label><br/>
                <textarea id='gene' rows="10" cols="50" name="gene_ids" required></textarea>  <!-- required 属性规定必需在提交之前填写输入字段。 -->
                <br/>
                <span>
                    e.g.,&nbsp;<a href="#"><em id="eg_gene">TEA000001.1,TEA033022.1,TEA000025.1,TEA000103.1</em></a>
                </span>
            </div>
            <div>
                {% csrf_token %}
                <input type="submit" value="search" name='submitBtn' id="sub"/>
            </div>
        </form>
    </div>
</body>
</html>